services:
  nginx-prod:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: nginx-prod
    ports:
      - "8080:80"
    volumes:
      - ../../html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    restart: unless-stopped
    networks:
      - prod-network
    depends_on:
      - api-prod

  api-prod:
    build: ../../api
    container_name: api-prod
    ports:
      - "5001:5000"
    environment:
      DB_HOST: ${DB_HOST_PROD}
      DB_PORT: ${DB_PORT_PROD:-5432}
      DB_USER: ${DB_USER_PROD}
      DB_PASSWORD: ${DB_PASSWORD_PROD}
      DB_NAME: ${DB_NAME_PROD}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_TO: ${MAIL_TO}
    restart: unless-stopped
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge